#!/bin/bash

if [ ! -f .commit_generated ]; then
	exit 0
fi

if [ -z "$(which jq)" ] || [ -z "$(which jsonnet)" ]; then
	echo "please install jsonnet and jq"
	exit 1
fi

for f in _generated/*.jsonnet; do
	git rm -f $f >/dev/null 2>&1 || true
done

for row in $(jsonnet root.jsonnet | jq -r '.[] | @base64'); do
	_jq() {
		echo "${row}" | base64 --decode | jq -j ${1}
	}
	_gen_file=_generated/$(_jq '(.kind|ascii_downcase),"-",.metadata.name').jsonnet
	_jq '.' >"${_gen_file}"
	git add -v "${_gen_file}" >/dev/null 2>&1
done

if [ $(git diff --name-only --cached | wc -l) -gt 0 ]; then
	git commit --amend -C HEAD --no-verify
fi

rm .commit_generated 2>/dev/null || true
